### ISSUE TITLE
Potential bug in OrderBookStore.d.ts:OrderBookStore:handleSnapshot - data parameter should be of type OrderBookLevelState[] instead of OrderBookLevelState

### ISSUE THREAD

**Issue by shaigr** [tiagosiebler/orderbooks#15]
I'll submit a pull request for your review.
Thanks,
Shai

**Comment by tiagosiebler** [comment]
Looks like you're right, somehow missed that when converting this to typescript 🤦 will review the PR once ready - thanks

**Comment by tiagosiebler** [comment]
Released with v1.1.4. Thanks for reporting this & fixing it!
