### ISSUE TITLE
Sample for V5

### ISSUE THREAD

**Issue by emorling** [tiagosiebler/orderbooks#18]
This seems to be a very useful library! Does anyone have a sample with ByBit sockets V5?

**Comment by n3xtgen** [comment]
Hi, I would also like to migrate to ByBit v5 Websocket but it looks like the format of delta update has been changed. @tiagosiebler  Are you planning to do some implementation?
Or does anyone know where to find information how to construct the current state of OrderBook after delta updates. Makes me mad that there is no official ByBit suggestion how to do it in their documentation, like it isnt the first thing everyone would ask..

**Comment by tiagosiebler** [comment]
No immediate plans on my end but it should be possible to implement the delta + snapshots without changes to this package (but please correct me if that's wrong). The v2 bybit websockets also used deltas and snapshots, and typically it's just a matter of mapping the exchange-format to the format understood by this package. Here's the v2 sample:
https://github.com/tiagosiebler/orderbooks/blob/master/samples/bybit.js

**Comment by tiagosiebler** [comment]
Some discussion here, in case anyone wants to work on adding a sample: https://github.com/tiagosiebler/bybit-api/issues/246

**Comment by JJ-Cro** [comment]
I updated bybit v5 websockets  to this file, it seems to work okay : https://github.com/tiagosiebler/awesome-crypto-examples/blob/master/src/exchanges/bybit/orderbooks/local-orderbook.ts 

You can use whole file or reuse some parts!

**Comment by tiagosiebler** [comment]
Thanks @JJ-Cro - closing this but feel free to create new issues for anything else for the repo
